# Nginx
#
# VERSION 0.0.1

ARG VERSION=latest
FROM nginx:$VERSION
LABEL maintainer "Dmitri G. <dimi615@pisem.net>"

# LABEL Description="This image is used to start my Nginx virtual server" Vendor="Private Co., Ltd" Version="0.0.1"
# Working directory initialisation
# WORKDIR /root/

# Add some config files
COPY [".bashrc","/root/"]

